version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./entornosapp:/home/entornosapp  # Monta el directorio local 'entornosapp' en '/home/entornosapp' del contenedor
    command: tail -f /dev/null  # Evita que el contenedor se cierre inmediatamente
